Travelopia/web-components

package-lock.json
package.json
src/multi-select/README.md
src/multi-select/index.html
src/multi-select/index.ts
src/multi-select/style.scss
src/multi-select/tp-multi-select-field.ts
src/multi-select/tp-multi-select-option.ts
src/multi-select/tp-multi-select-options.ts
src/multi-select/tp-multi-select-pill.ts
src/multi-select/tp-multi-select-pills.ts
src/multi-select/tp-multi-select-placeholder.ts
src/multi-select/tp-multi-select-search.ts
src/multi-select/tp-multi-select-select-all.ts
src/multi-select/tp-multi-select-status.ts
src/multi-select/tp-multi-select.ts
webpack.config.js

Multi Select Component

---

src/multi-select/tp-multi-select.ts

There is a bug in `tp-multi-select` that `selected` attribute is not applied on `option` element when any `tp-multi-select-option` is selected.
https://github.com/Travelopia/web-components/assets/60139930/78344770-d773-4a40-a324-ed41e17c58ff

Apply `selected` attribute on option during initialization

---

src/multi-select/index.html
src/multi-select/style.scss
src/multi-select/tp-multi-select-select-all.ts
src/multi-select/tp-multi-select.ts

This PR adds a disabled option support in `tp-multi-select`.
- An attribute `disabled` should be set with value `yes` in order to disable an option in the multi-select. This will prevent that option from getting selected. 
- In case of select all or deselect all, this option should not be checked.

Add disabled options support in `tp-multi-select`

---

src/slider/tp-slider.ts

- Sometimes we the next slide-index before the slide changes. The getCurrentSlide() does not give that information.  
- This PR Adds index on 'slide-set' event in event details.

Add Index On 'slide-set' Event

---

src/multi-select/style.scss
src/multi-select/tp-multi-select-field.ts
src/multi-select/tp-multi-select-option.ts
src/multi-select/tp-multi-select-pill.ts
src/multi-select/tp-multi-select-pills.ts
src/multi-select/tp-multi-select-search.ts
src/multi-select/tp-multi-select-select-all.ts
src/multi-select/tp-multi-select.ts

This PR updates the multi-select component which fixes following bugs - 
1. `update` function is triggered on initialization for main component and the pills component in-order to update the selected options.
2. To avoid submitted the first option, the code has been refactored specifically the `updateFormField` method. We are now creating `select` option dynamically on user's selection. By default, a select will be rendered without any option. If a user selects a `tp-multi-select-option`, we update the DOM by appending a option to it. If de-selected, we remove the same. Also, during the first load, if some tp-options are already selected, we update the `select` tag as well.
3. With respect to [this bug](https://github.com/Travelopia/web-components/issues/15#issuecomment-1872987098), code …

Update Multi-select component

---

package.json
src/multi-select/tp-multi-select-option.ts
src/multi-select/tp-multi-select-search.ts

- Fixes the search issue. It was searching by value instead of label and space had to be accounted for in the search value.

Multi Select: Fix search issue

---

package.json
src/multi-select/tp-multi-select-search.ts

- When the user selected an option after a search, the search results were not getting refreshed (to show all options)and were still showing the old results.
- When the options are opened, ensure we get fresh results.

Update Multi-Select Component Search

---

package.json
src/slider/style.scss

- When using fade mode of the slider, the adding hover state on the selected slider does not work because of the z-index issue.
- This PR fixes the z-index issue by giving a high z-index to the selected slide.

Fix Slider Component CSS

---

package.json
src/slider/index.html
src/slider/tp-slider.ts

- The disabled attribute was not working in the case of the nested slider because since querySelector was used it would find the first instance of the arrow which was from the inner slider instead of parent slider arrow.
- This PR fixes that issue by checking if the parent `tp-slider` of the arrow element is same as `this`. If it is then that means we have found the correct arrow element.
- we cannot use CSS for this because the user can keep the arrows anywhere they want.

TPSlider: Fix slider arrows

---

src/slider/index.html
src/slider/tp-slider.ts

1. Fix resize race condition. Fixes #28 
2. Fix slider with non-flexible height and fade behaviour

Slider Component Fixes

---

package-lock.json
package.json
src/multi-select/tp-multi-select-field.ts
src/multi-select/tp-multi-select-option.ts

When re-attaching the `multi-select` component inside the DOM, the `connectedCallback` of the components run again and duplicate event listeners are added to the component.
To fix this add a check in the `connectedCallback` that - "if the component is already initialized don't add the event listeners again.
Reference issue - https://github.com/Travelopia/web-components/issues/35

Fix duplicate event listeners in multi-select component

---

package.json
src/multi-select/tp-multi-select-pill.ts

Problem: When enter key is pressed it clears the previous selection.
This PR fixes the above issue.

Fix Multi-Select

---

src/slider/README.md
src/slider/index.html
src/slider/tp-slider.ts

Fixes https://github.com/Travelopia/web-components/issues/47

Add auto slide support to TP slider

---

src/multi-select/tp-multi-select-search.ts

Fix Multi Select Event Conflict

---

package-lock.json
package.json
src/multi-select/index.html
src/multi-select/tp-multi-select-pill.ts
src/multi-select/tp-multi-select-pills.ts
src/multi-select/tp-multi-select-search.ts

Cross-browser solution to remove pills correctly without submitting the form.
Fixes issues introduced in https://github.com/Travelopia/web-components/releases/tag/0.5.18

Fix: Multi-Select Cross Browser Pill Remove

---

src/slider/README.md
src/slider/index.html
src/slider/tp-slider-count.ts
src/slider/tp-slider.ts

- Addresses #43 issue of adding `slides-per-view` and `step` in slider.

Add `slides-per-view` and `step` in slider

---

src/lightbox/README.md
src/lightbox/index.html
src/lightbox/index.ts
src/lightbox/style.scss
src/lightbox/tp-lightbox-close.ts
src/lightbox/tp-lightbox-content.ts
src/lightbox/tp-lightbox-count.ts
src/lightbox/tp-lightbox-next.ts
src/lightbox/tp-lightbox-previous.ts
src/lightbox/tp-lightbox-trigger.ts
src/lightbox/tp-lightbox.ts
webpack.config.js

Lightbox Component

---

src/accordion/tp-accordion-collapse-all.ts
src/accordion/tp-accordion-expand-all.ts
src/accordion/tp-accordion-handle.ts
src/accordion/tp-accordion-item.ts
src/form/tp-form-field.ts
src/form/tp-form.ts
src/modal/tp-modal-close.ts
src/modal/tp-modal.ts
src/multi-select/tp-multi-select-field.ts
src/multi-select/tp-multi-select-option.ts
src/multi-select/tp-multi-select-pill.ts
src/multi-select/tp-multi-select-pills.ts
src/multi-select/tp-multi-select-search.ts
src/multi-select/tp-multi-select-select-all.ts
src/multi-select/tp-multi-select.ts
src/slider/tp-slider-arrow.ts
src/slider/tp-slider-nav-item.ts
src/slider/tp-slider-slide.ts
src/tabs/tp-tabs-nav-item.ts
src/tabs/tp-tabs.ts

Move all events to constructor to avoid duplicate event listeners.

Move events to constructor

---

package.json
src/slider/README.md
src/slider/index.html
src/slider/tp-slider.ts

**Issue:** The slider moves to the next/prev slide when the user scrolls vertically.
This PR adds feature to move the slides only if it's a horizontal scroll and in-case if the user swipes diagonally, we have a threshold after which it will not move the slide.

Fix: TP Slider Swipe Issue

---

src/multi-select/README.md
src/multi-select/tp-multi-select.ts

Added `form` attribute to the `tp-multi-select` component to add ability to link it with a form without using JavaScript.

Add form reference attribute to tp-multi-select

---

src/slider/tp-slider.ts

The default value of `swipeThreshold` is 200. Because of an incorrect check for the next swipe, the user has to scroll more than the threshold value to swipe to the next slide.
The condition has to be reversed because `swipeDistanceX` will be negative in case of the next slide swipe.

Fix Swipe Condition of Next Slide

---

src/multi-select/tp-multi-select-pills.ts

The pill removal button isn't working because the `addEventListener` added to the remove button in `tp-multi-select-pill` is added in the `constructor` instead of `connectedCallback`. The constructor is called when the pill is created, but that instance doesn't include the remove button as a child. As a result, no `addEventListener` is attached to the pill remove button.
I see two possible solutions:

Fix Multi-select Pill Remove 

---

src/multi-select/tp-multi-select.ts

The input value will not get included in form submission if the form attribute is an empty string. Fixing this requires checking the attribute to see if it is empty or not.

Fix: Form reference bug in tp-multi-select

---

src/slider/tp-slider-count.ts
src/slider/tp-slider-nav-item.ts
src/slider/tp-slider.ts

Fix Slider Next action when per-view is added.

Fix Slider Next action when per-view is added

---

src/number-spinner/README.md
src/number-spinner/index.html
src/number-spinner/index.ts
src/number-spinner/style.scss
src/number-spinner/tp-number-spinner-decrement.ts
src/number-spinner/tp-number-spinner-increment.ts
src/number-spinner/tp-number-spinner-input.ts
src/number-spinner/tp-number-spinner.ts
webpack.config.js

https://github.com/Travelopia/web-components/issues/80

Web component: Number Spinner

---

src/slider/index.ts

Fixes #86 
- The update method in the tp-slider-count component throws a TypeError: e.getTotalSlides is not a function. This occurs because the getTotalSlides method is being called on a tp-slider element before the required JavaScript for the slider has been loaded, leading to the method being undefined at the time of invocation.
- This PR resolves the issue by ensuring the necessary JavaScript for the tp-slider component is loaded and initialized before any method calls are made.

Fix: Handle missing getTotalSlides method in slider

---

src/lightbox/README.md
src/lightbox/index.html
src/lightbox/index.ts
src/lightbox/tp-lightbox-nav-item.ts
src/lightbox/tp-lightbox-nav.ts
src/lightbox/tp-lightbox.ts

resolves #92 
Add support of navigation bullets/dots to jump over any slide.
Add two subcomponent to tp-lightbox component.
Add event `slide-set` when slide get updated.

Add Lightbox nav items

---

src/lightbox/index.html
src/lightbox/tp-lightbox-nav.ts

Dynamic lightbox navigation injection

---

src/multi-select/index.html
src/multi-select/tp-multi-select-pills.ts

Fixes #71 & partially fixes #26

Fix: Multi-Select - Allow unique pills incase of duplicate values

---

src/slider/tp-slider-nav-item.ts
src/slider/tp-slider-nav.ts
src/slider/tp-slider.ts

This PR aims to work with nav items and highlight items.

WP-184 Slide Nav Items Creation and Highlight

---

src/slider/tp-slider-slide.ts
src/slider/tp-slider-slides.ts
src/slider/tp-slider.ts

This PR aims to fix the issue when responsive settings don't get applied with the provided breakpoints. 
Functionality of calling the handleResize function is migrated from the slide component to the slides component.

WP-204 Responsive settings not applied on breakpoint changes in <tp-slider> component
